import Head from "next/head";
import {  Container } from "@mantine/core";
import AppShellDemo from "../components/AppShell";


export default function Home() {

  const page = () => {
    return (
      <Container>
        <p>Hola mundo</p>
      </Container>
    )
  }


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppShellDemo page={page}/>
    </>
  );
}